### ISSUE TITLE
ensure preview position matching the source cursor position is always visible

### ISSUE THREAD

**Issue by mark-hahn** [mark-hahn/markdown-scroll-sync#10]
This is especially important then the source file is smaller than the screen and the preview is larger than its screen.

**Comment by alim0x** [comment]
Thanks for your work first.
I don't know what the sync depends, but I think by line maybe is a good choice.
Now if I have an article, there is many pics between the first and second paragraphs, when I locate cursor in the second paragraph, the preview of the second paragraph will out of screen because of so many pics.

like this:  XD
![qq 20150429225408](https://cloud.githubusercontent.com/assets/4954007/7393855/bb4953a6-eec2-11e4-916b-40080a899781.jpg)

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.
