### ISSUE TITLE
Scrolling not quite synchronized

### ISSUE THREAD

**Issue by fredlebel** [mark-hahn/markdown-scroll-sync#3]
A large MD file will tend to lose sync offset as the file is scrolled down.  The offset can even grow as large as a full screen height.  I'm assuming this is due to a scroll sync based on an absolute position.

If possible, could it synchronize based on a percentage of the position in the file instead?  That way, scrolling even 90% would still be accurate.  Scrolling to the bottom would synchronize to the bottom of the preview.

**Comment by mark-hahn** [comment]
> I'm assuming this is due to a scroll sync based on an absolute position.

It's based on the html element in the DOM.  It should match.  I have some
bug.  Can you please email the example file to me at mark@hahnca.com?

> , could it synchronize based on a percentage of the position in the file
instead?

That wouldn't work.  Imagine how an image could be one line in the source
file and two screens high in the preview.

**Comment by fredlebel** [comment]
Try this MD as an example: https://github.com/baskerville/bspwm/blob/master/doc/bspwm.1.txt

**Comment by mark-hahn** [comment]
Thanks.  I'll work on this tomorrow.

**Comment by mark-hahn** [comment]
I improved the accuracy of the sync in your file until I got to the first instance of `~~~~~~`.  This is not meaingful markdown.  `~~` is meant to surround strike-out text.  So having three of these in a row would mean the text following is to be strike-through.  However markdown-preview screws up and shows the following text as a `code` block.   If you remove all those tildes everything works great. You can see this for yourself.  

Since everything is screwed up I can't sync it.   Sorry. I would suggest submitting an issue to `atom/markdown-preview`.  

Thanks again.  I wouldn't have learned any of this without your help.

I have released the improved syncing version as 0.2.0
